### ISSUE TITLE
The "DDIM" mode in continuous sampler

### ISSUE THREAD

**Issue by placeforyiming** [kazuto1011/r2dm#6]
Hi，

Thanks for open-source such a well-organized code-base, it's really helpful!

I have a question about the "DDIM" mode in the continuous sampler.  I just notice this part seems be deleted in the new commit, is there some further improvements about this part? In the previous commit, I think the σ in the equation below is missing in the p_sample, not sure if this is the point?

![20240407-115302](https://github.com/kazuto1011/r2dm/assets/22132384/4f5be87f-8333-49cf-a456-1631bc4c0b29)

Looking forward your reply,
thanks

**Comment by kazuto1011** [comment]
Thank you for your interest! I accidentally released the unfinished DDIM implementation in this repository, and I have deleted it to avoid confusion since I did not use DDIM for our paper.

Anyway, I have implemented the continuous-time version (f0c8b43af6d0ab5648fe3ea12f2fefed94731d90), according to the following differences in the $q$ notation,
* Discrete-time: $q(z_t|x)=\mathcal{N}(\sqrt{\alpha_t} x, (1-{\alpha_t}) I)$
* Continuous-time: $q(z_t|x)=\mathcal{N}(\alpha_t x, \sigma_t^2 I)$

|DDPM 64 steps|DDIM 64 steps ($\eta=0$)|
|:-:|:-:|
|![samples_ddpm](https://github.com/kazuto1011/r2dm/assets/9032347/6c16d4b3-07b2-41de-8669-101be524d0ab)|![samples_ddim](https://github.com/kazuto1011/r2dm/assets/9032347/05245ada-de25-4e1d-bbac-930f1a586194)|
